apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-aws-upbound
  namespace: crossplane
spec:
  endpoint:
    hostnameImmutable: true
    url: 
      type: Static
      static: http://crossplane-localstack:4566
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane
      name: aws-secret
      key: creds
