apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: crossplane
type: Opaque
data:
  # This is just test/test.
  creds: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gdGVzdAphd3Nfc2VjcmV0X2FjY2Vzc19rZXkgPSB0ZXN0Cg==