---
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-aws-community
  namespace: crossplane
spec:
  endpoint:
    hostnameImmutable: true
    url: 
      type: Static
      static: http://crossplane-localstack:4566
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane
      name: aws-secret
      key: creds
---
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: bucket1
  namespace: crossplane
spec:
  forProvider:
    locationConstraint: us-east-1
    acl: public-read
  providerConfigRef:
    name: provider-aws-community